/*
 * CBSE GPL Source Code
 * Copyright (C) 2018  Unreal Arena
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#ifndef TEAM_COMPONENT_H_
#define TEAM_COMPONENT_H_

#include "../backend/CBSEBackend.h"
#include "../backend/CBSEComponents.h"

class TeamComponent: public TeamComponentBase {
	public:
		// TODO: Move the team_t enum here.
		typedef team_e team_t;

		// ///////////////////// //
		// Autogenerated Members //
		// ///////////////////// //

		/**
		 * @brief Default constructor of the TeamComponent.
		 * @param entity The entity that owns the component instance.
		 * @param team An initialization parameter.
		 * @note This method is an interface for autogenerated code, do not modify its signature.
		 */
		TeamComponent(Entity& entity, team_t team);

		// ///////////////////// //

		team_t Team() const { return team; }

		bool operator==(const TeamComponent& other) const {
			return Team() == other.Team();
		}

		bool operator!=(const TeamComponent& other) const {
			return !(*this == other);
		}

	private:

};

#endif // TEAM_COMPONENT_H_
